# Generated by Django 3.0.8 on 2020-08-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keepnote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
