# Generated by Django 3.0.8 on 2020-08-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import keepnote.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keepnote', '0005_auto_20200825_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadInNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.ImageField(blank=True, null=True, storage=keepnote.models.MyStorage(), upload_to=keepnote.models.get_upload_path)),
                ('noteid', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
