# Generated by Django 3.0.8 on 2020-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepnote', '0008_auto_20200825_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
