# Generated by Django 3.0.8 on 2020-08-27 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepnote', '0009_auto_20200825_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 28, 33, 538342)),
        ),
    ]
