# Generated by Django 3.0.8 on 2020-08-27 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keepnote', '0010_note_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 20, 30, 15, 859982)),
        ),
        migrations.AlterField(
            model_name='note',
            name='flag',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
