# Generated by Django 2.1.5 on 2020-07-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='codeurl',
            field=models.URLField(blank=True),
        ),
    ]
