# Generated by Django 3.0.8 on 2020-07-20 16:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
