# Generated by Django 3.0.8 on 2020-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200720_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='monile',
            field=models.IntegerField(null=True),
        ),
    ]
