# Generated by Django 3.0.8 on 2020-07-20 16:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200720_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='age',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='monile',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='about',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
