# Generated by Django 3.0.8 on 2020-07-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200720_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='about',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='about',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
