# Generated by Django 3.0.8 on 2020-07-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200720_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='awardsWon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='completedProject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='jobStarted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='users',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
