# Generated by Django 3.0.8 on 2020-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200720_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='about',
            name='jobStarted',
        ),
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='yearOfExperience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
