# Generated by Django 3.0.8 on 2020-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='award',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
    ]
