# Generated by Django 3.0.8 on 2020-07-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deleteTodoOrNot',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=False),
        ),
    ]
