# Generated by Django 3.0.8 on 2020-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='todoid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
