# Generated by Django 3.0.8 on 2020-07-31 08:23

from django.db import migrations, models
import todowoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0006_todo_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uploadFile',
            field=models.FileField(blank=True, null=True, upload_to=todowoo.models.get_upload_path),
        ),
    ]
