# Generated by Django 3.0.8 on 2020-07-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0007_auto_20200731_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
