# Generated by Django 3.0.8 on 2020-07-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0010_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
