# Generated by Django 3.0.8 on 2020-08-02 06:12

from django.db import migrations, models
import todowoo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0013_auto_20200731_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uploadFile',
            field=models.FileField(blank=True, null=True, upload_to=todowoo.models.get_upload_path),
        ),
    ]
