# Generated by Django 3.0.8 on 2020-08-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0016_auto_20200802_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
