# Generated by Django 3.0.8 on 2020-08-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todowoo', '0018_auto_20200802_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='username',
            new_name='user',
        ),
    ]
